version: "3.8"

services:
  web:
    image: webserver-glpi:1.1
    ports:
      - "80:80"
    depends_on:
      - db
    restart: always

  db:
    image: mysql:latest
    ports:
      - "3306"
    restart: always
    volumes:
      - ./mysql/create.sql :/docker-entrypoint-initdb.d/create.sql
    environment:
      MYSQL_ROOT_PASSWORD: glpi
      MYSQL_DATABASE: glpi
      MYSQL_USER: glpi
      MYSQL_PASSWORD: glpi



