version: "3.8"

services:
  db:
    image: mysql:latest
    container_name: glpi-mysql
    ports:
      - "3306"
    restart: always
    volumes:
      - ./initdb:/docker-entrypoint-initdb.d
      - /backup:/backup
    environment:
      MYSQL_ROOT_PASSWORD: glpi
      MYSQL_DATABASE: glpi
      MYSQL_USER: glpi
      MYSQL_PASSWORD: glpi
      TZ: America/Sao_Paulo
  
  web:
      image: glpi-docker:1.2
      container_name: glpi-web-server
      ports:
        - "80:80"
        - "443:443"
      depends_on:
        - db
      restart: always
      environment:
        - GLPI_DB_HOST=db
        - GLPI_DB_NAME=glpi
        - GLPI_DB_USER=glpi
        - GLPI_DB_PASSWORD=glpi
      volumes:
        - /var/www/:/var/www/
        - /backup:/backup

volumes:
    mysql:
    glpi:

