version: "3"

services:
  web:
    image: webserver-glpi:1.1
    ports:
      - "80:80"
    depends_on:
      - db

  db:
    image: mysql:latest
    ports:
      - "3306"
    environment:
      MYSQL_ROOT_PASSWORD: glpi
      MYSQL_DATABASE: glpi
      MYSQL_USER: glpi
      MYSQL_PASSWORD: glpi
