version: "3"

services:
  db:
    image: mysql:latest
    container_name: glpi-mysql
    ports:
      - "3306"
    restart: always
    volumes:
      - ./initdb:/docker-entrypoint-initdb.d
      - /var/lib/mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: glpi
      MYSQL_DATABASE: glpi
      MYSQL_USER: glpi
      MYSQL_PASSWORD: glpi
      TZ: America/Sao_Paulo
  web:
      image: glpi-docker:latest
      container_name: glpi-web-server
      ports:
        - "80:80"
        - "443:443"
      restart: always
      depends_on:
        - db
      volumes:
        - /var/www/:/var/www/
      environment:
        GLPI_DB_HOST: db
        GLPI_DB_NAME: glpi
        GLPI_DB_USER: glpi
        GLPI_DB_PASSWORD: glpi
