version: "3.8"

services:
  web:
    image: glpi-docker:1.2
    ports:
      - "80:80"
    depends_on:
      - db
    restart: always

  db:
    image: mysql:latest
    ports:
      - "3306"
    restart: always
    volumes:
      - ./mysql:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: glpi
      MYSQL_DATABASE: glpi
      MYSQL_USER: glpi
      MYSQL_PASSWORD: glpi

volumes:
    mysql:

