version: "3"

services:
  web:
    image: webserver-glpi:1.1
    
    restart_policy:
      condition: on-failure
    ports:
      - "80:80"
    depends_on:
      - db

  db:
    image: mysql:latest
    ports:
      - "3306"
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: glpi
      MYSQL_USER: glpi
      MYSQL_PASSWORD: glpi
